# Plungin TransportBukkit

# Default language
lang: en_US

# Auto save delay for Vehicles
saveDelay: 10
# Auto save delay when a vehicle is moving
lazySaveDelay: 600

# Save the templates of the plugin on reload
save_default_templates: false
always_save_lang: false

command_aliases:
  - vehicle
